version: '3'
services: 
  web: 
    image: eleonorebergqvist/laravel-docker-scaffold
    build: src
    tty: true
    volumes:
      - "./src:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
  db: 
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=laravel
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel