version: '3'
services: 
  web: 
    image: eleonorebergqvist/receptplaneraren
    build: src
    tty: true
    volumes:
      - "./src:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db: 
    image: mysql:5
    ports:
        - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=laravel
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    volumes:
      #- "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
      - "./db/:/var/lib/mysql"
    user: "1000:50"
    # CREATE DATABASE IF NOT EXISTS laravel_test; GRANT ALL PRIVILEGES ON laravel_test.* TO 'laravel'@'%';