version: 2

defaults: &defaults
  working_directory: ~/repo

filter_only_develop_or_tag: &filter_only_develop_or_tag
  filters:
    branches:
      only:
        - develop
    tags:
      only:
        - /^v.*/

references:
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}

jobs:
  checkout_code:
    <<: *defaults
    docker:
      - image: circleci/node:latest
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mysql:5
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

  frontend:
    <<: *defaults
    docker:
      - image: circleci/node:latest
    steps:
      - *restore_repo
      - restore_cache:
          key: v1-npm-{{ checksum "frontend/package.json" }}
      - run: cd frontend && npm ci
      - save_cache:
          key: v1-npm-{{ checksum "frontend/package.json" }}
          paths:
            - ~/repo/frontend/node_modules
      - run:
          command: |
            cd frontend
            npm test

  laravel:
    <<: *defaults
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mysql:5
        environment:
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
          MYSQL_ROOT_PASSWORD: laravel
    steps:
      - *restore_repo
      - run: sudo apt install -y zlib1g-dev
      - run: sudo composer self-update
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: cd src && cp .env.circleci .env
      - run: cd src && cp .env.circleci .env.testing
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "src/composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
      - run: cd src && composer install -n --prefer-dist
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "src/composer.lock" }}
          paths:
            - src/vendor
      - run: cd src && php artisan migrate --database=mysql --force
      - run: cd src && php artisan key:generate
      - run:
          name: Create SPA index file required for test suite
          command: mkdir src/public && echo "<html><body><div>app</div></body></html>" > src/public/index.html
      - run: cd src && php vendor/bin/phpunit

  deploy:
    <<: *defaults
    docker:
      - image: buildpack-deps:trusty
    steps:
      - *restore_repo
      - restore_cache:
          key: v1-assets-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy application to Heroku
          command: |
            #git push https://heroku:$HEROKU_API_KEY@git.heroku.com/receptplaneraren-staging.git master
            git subtree push --prefix src https://heroku:$HEROKU_API_KEY@git.heroku.com/receptplaneraren-staging.git master

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - frontend:
          requires:
            - checkout_code
      - laravel:
          requires:
            - checkout_code
      - deploy:
          #<<: *filter_only_develop_or_tag
          requires:
            - frontend
            - laravel

